version: "3.7"
services:

    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: eco-choice-api
        container_name: eco-choice-api-app
        restart: unless-stopped
        tty: true
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - eco-choice-api

    db:
        image: mysql:5.7
        container_name: eco-choice-api-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - eco-choice-api

    nginx:
        image: nginx:1.17-alpine
        container_name: eco-choice-api-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - eco-choice-api

networks:
    eco-choice-api:
        driver: bridge
